Algoritmo "professores se"
Var
   nome : caractere
Inicio
   escreval("Digite o nome do Professor(a):")
   leia(nome)
   se nome = "Higor" entao
      escreval("Docente")
   senao
      se nome = "Mikelly" entao
         escreval("Professora")
      senao
         se nome = "Dalto" entao
            escreval("Professor")
         senao
            escreval("Professor não cadastrado")
         fimse
      fimse
   fimse
Fimalgoritmo