Algoritmo "Dia da semana - escolha"
// Desenvolva um programa em VisuAlg (com se e escolha)
// e o fluxograma que leia o dia da semana em número
Var
   dia : inteiro
Inicio
   escreval("Digite o dia em número:")
   leia(dia)
   escolha dia
   caso 1 // eq: se igualdade(var = valor) entao
      escreval("Domingo")
   caso 2
      escreval("Segunda")
   caso 3
      escreval("Terça")
   caso 4
      escreval("Quarta")
   caso 5
      escreval("Quinta")
   caso 6
      escreval("Sexta")
   caso 7
      escreval("Sábado")
   outrocaso //eq: equivalente ao ultimo senão
      escreval("Inválido")
   fimescolha
Fimalgoritmo